version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
              sudo pip install pytest pytest-cov
      - run:
          command: pytest --cov-report=xml > .coverage
          name: Test
      - codecov/upload:
          file: .coverage

workflows:
  main:
    jobs:
      - build-and-test
