version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2


jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest --cov=./
          name: Test
      - codecov/upload:
          file: {{ coverage_report_filepath }}

workflows:
  main:
    jobs:
      - build-and-test
