version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker cp ./ /source
      - run:
          command: docker-compose -f docker/docker-compose.yml up -d

workflows:
  main:
    jobs:
      - build-and-test
