version: '3.3'

services:
  beam-sink:
    image: python3.7
    environment:
      PYPIUSER: ${PYPIUSER}
      PYPIPASSWORD: ${PYPIPASSWORD}

    volumes:
      - .:/source

    entrypoint: /source/.github/workflow/run-tests.sh

  mysql:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'thrillhouse'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3306:3306'