name: Run Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Stop MySQL
      run: |
        sudo /etc/init.d/mysql stop
    - name: Run Docker
      run: docker-compose -f docker/docker-compose.yml up -d